# Natural Language Processing (NLP) with Tensorflow

# Latihan Tokenization

In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [2]:
tokenizer = Tokenizer(num_words=15, oov_token='-')

In [3]:
teks = ['Saya suka programming',
        'Programming sangat menyenangkan!',
        'Machine Learning berbeda dengan pemrograman konvesional']

In [4]:
tokenizer.fit_on_texts(teks)

In [5]:
sequences = tokenizer.texts_to_sequences(teks)

In [6]:
print(tokenizer.word_index)

{'-': 1, 'programming': 2, 'saya': 3, 'suka': 4, 'sangat': 5, 'menyenangkan': 6, 'machine': 7, 'learning': 8, 'berbeda': 9, 'dengan': 10, 'pemrograman': 11, 'konvesional': 12}


In [7]:
print(tokenizer.texts_to_sequences(['Saya suka programming']))
print(tokenizer.texts_to_sequences(['Saya suka belajar programming sejak SMP']))

[[3, 4, 2]]
[[3, 4, 1, 2, 1, 1]]


In [8]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences_samapanjang = pad_sequences(sequences)

In [9]:
print(sequences_samapanjang)

[[ 0  0  0  3  4  2]
 [ 0  0  0  2  5  6]
 [ 7  8  9 10 11 12]]


In [10]:
sequences_samapanjang = pad_sequences(sequences,
                                      padding='post',
                                      maxlen=5)

In [11]:
sequences_samapanjang = pad_sequences(sequences,
                                      padding='post',
                                      maxlen=5,
                                      truncating='post')

# Embedding

In [12]:
# model = tf.keras.Sequential([
#    tf.keras.layers.Embedding(jumlah_kata, dimensi_embedding, panjang_input),
#   tf.keras.layers.Flatten(),
#    tf.keras.layers.Dense(24, activation='relu'),
#    tf.keras.layers.Dense(1, activation='sigmoid')
# ])

In [13]:
# model.compile(loss='categorical_crossentropy',
#              optimizer='adam',
#              metrics=['accuracy'])

In [14]:
# model.fit(padded_latih, label_latih, 
#          epochs=num_epochs, 
#          validation_data=(padded_test, label_test))